'use client';
import { useEffect,useState } from 'react';
import './styles.css';

const features=[
 ['Free Preview','Professional ₹499','Business ₹1,499'],
 ['Website growth score','✓','✓','✓'],['Basic SEO & technical checks','✓','✓','✓'],['Performance & mobile overview','✓','✓','✓'],['Accessibility overview','✓','✓','✓'],['Security overview','✓','✓','✓'],['Detailed PDF report','—','✓','✓'],['Deep findings & risk analysis','—','✓','✓'],['Prioritised recommendations','3 preview items','15+ detailed','25+ strategic'],['30-day action plan','—','✓','✓'],['Advanced content opportunities','—','✓','✓'],['Technical SEO opportunities','—','✓','✓'],['Conversion / lead-generation audit','—','—','✓'],['Commercial readiness analysis','—','—','✓'],['Strategic growth opportunities','—','—','✓'],['90-day business roadmap','—','—','✓'],['Recommended business KPIs','—','—','✓'],['Email delivery','—','✓','✓'],
];
const plans=[{id:'professional',name:'Professional Report',price:'₹499',desc:'Deep audit for owners who need a detailed improvement checklist.'},{id:'business',name:'Business Report',price:'₹1,499',desc:'Strategic audit for businesses focused on leads, conversion and growth.'}];
export default function Home(){
 const [url,setUrl]=useState('https://a2z-learning-solutions.vercel.app'),[data,setData]=useState(null),[loading,setLoading]=useState(false),[email,setEmail]=useState(''),[paying,setPaying]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(document.querySelector('script[src="https://checkout.razorpay.com/v1/checkout.js"]'))return;const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.async=true;document.body.appendChild(s)},[]);
 async function analyze(e){e.preventDefault();setLoading(true);setError('');setMessage('');setData(null);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})}),j=await r.json();if(!r.ok)throw Error(j.error||'Analysis failed');setData(j)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function buyReport(plan){if(!data)return setError('Analyze a website first.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return setError('Enter a valid email address.');setPaying(plan);setError('');setMessage('Creating secure payment order...');try{const r=await fetch('/api/payment/create-order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,url:data.url})}),o=await r.json();if(!r.ok)throw Error(o.error||'Could not create payment order.');if(!window.Razorpay)throw Error('Razorpay Checkout is still loading. Please try again.');const checkout=new window.Razorpay({key:o.keyId,amount:o.amount,currency:o.currency,name:'A2Z Learning Solutions',description:o.name,order_id:o.orderId,prefill:{email},notes:{website:data.url,plan},handler:async response=>{setMessage('Payment verified. Running deep analysis and generating your report...');try{const d=await fetch('/api/payment/deliver',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,url:data.url,...response})}),j=await d.json();if(!d.ok)throw Error(j.error||'Report delivery failed.');setMessage(j.message)}catch(e){setError(e.message);setMessage('')}finally{setPaying('')}},modal:{ondismiss:()=>{setPaying('');setMessage('')}}});checkout.open()}catch(e){setError(e.message);setMessage('');setPaying('')}}
 return <main><section className="hero"><div className="eyebrow">AI WEBSITE GROWTH & INTELLIGENCE PLATFORM</div><h1>Analyze, diagnose, recommend, improve, and <span>monitor growth.</span></h1><p>Get a free website growth score first. Upgrade to a genuinely deeper Professional or Business report with detailed insights, priorities and action plans.</p><form onSubmit={analyze}><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com"/><button disabled={loading}>{loading?'Analyzing...':'Analyze website →'}</button></form>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}</section>
 <section className="comparison"><div className="sectionIntro"><div className="eyebrow">WHAT CUSTOMERS GET</div><h2>Free preview vs paid reports</h2><p>The paid reports are not just unlocked versions of the free screen. Payment triggers a fresh server-side analysis and generates a deeper, plan-specific report.</p></div><div className="tableWrap"><table><thead><tr>{features[0].map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{features.slice(1).map((row,i)=><tr key={i}><td>{row[0]}</td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td></tr>)}</tbody></table></div></section>
 {data&&<section className="results"><div className="scoreCard"><div className="score">{data.score}</div><div><strong>Free website growth score</strong><p>{data.url}</p><small>HTTP {data.status} · {data.elapsed} ms analyzer response</small></div></div><div className="panel reportActions"><h2>Unlock your deeper report</h2><p>Enter your email. After Razorpay payment, the server performs a fresh analysis and builds your selected report.</p><div className="actionRow"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="your@email.com"/><span className="secureNote">🔒 Secure Razorpay payment</span></div><div className="planGrid">{plans.map(p=><article className="planCard" key={p.id}><div><h3>{p.name}</h3><strong>{p.price}</strong></div><p>{p.desc}</p><button onClick={()=>buyReport(p.id)} disabled={!!paying}>{paying===p.id?'Opening Razorpay...':`Pay ${p.price} & get report`}</button></article>)}</div></div><div className="panel highlight"><h2>Free preview</h2><div className="pillRow">{data.reportHighlights.slice(0,6).map(x=><span className="pill" key={x}>{x}</span>)}</div></div><div className="grid"><div className="panel"><h2>Audit overview</h2>{data.checks.slice(0,8).map((c,i)=><div className="check" key={i}><span className={c.pass?'dot pass':'dot fail'}>{c.pass?'✓':'!'}</span><div><b>{c.label}</b><small>{c.area} · {c.detail}</small></div></div>)}</div><div className="panel"><h2>Preview recommendations</h2>{data.suggestions.slice(0,3).map((s,i)=><div className="suggestion" key={i}><div className="tag">{s.area}</div><b>{s.title}</b><p>{s.advice}</p></div>)}</div></div></section>}
 <footer>Built for practical website improvement. Paid reports are generated after verified Razorpay payment.</footer></main>}
