function clamp(n, min = 0, max = 100) { return Math.max(min, Math.min(max, Math.round(Number(n) || 0))); }
function grade(score) { if (score >= 90) return 'Excellent'; if (score >= 75) return 'Strong'; if (score >= 60) return 'Needs improvement'; if (score >= 40) return 'Weak'; return 'Critical'; }
function priority(score) { if (score < 50) return 'Critical'; if (score < 70) return 'High'; if (score < 85) return 'Medium'; return 'Low'; }

export function buildPremiumReport(data, plan = 'professional') {
  const s = data.auditSummary || {}, summary = data.summary || {}, checks = data.checks || [];
  const failed = checks.filter(c => !c.pass), passed = checks.filter(c => c.pass);
  const categoryRows = ['seo','performance','mobile','accessibility','security','content','technical'].map(key => ({ key, name: key[0].toUpperCase()+key.slice(1), score: clamp(s[key]), grade: grade(s[key]), priority: priority(s[key]) }));
  const strengths = passed.slice(0, 10).map(c => `${c.label}: ${c.detail}`);
  const risks = failed.slice(0, 15).map(c => ({ area:c.area, issue:c.label, impact:c.detail }));
  const recommendations = (data.suggestions || []).map((item,i) => ({ rank:i+1, priority:priority(categoryRows.find(c=>c.name===item.area)?.score||50), area:item.area, title:item.title, advice:item.advice, outcome:`Improving ${item.title.toLowerCase()} should strengthen ${item.area.toLowerCase()} quality and reduce avoidable user or search-engine friction.` }));
  const contactSignals = Number(summary.forms||0)+Number(summary.phoneLinks||0)+Number(summary.whatsappLinks||0);
  const contentOpportunities = [!summary.description&&'Add a benefit-led meta description with a clear action.',!summary.ogTitle&&'Add Open Graph title and description for stronger social sharing.',Number(summary.words||0)<600&&'Expand important landing-page sections around customer problems, benefits, proof, FAQs and objections.',Number(summary.h1||0)!==1&&'Create a single descriptive H1 aligned with page search intent.',!summary.schema&&'Add relevant structured data to improve machine understanding and eligible search features.'].filter(Boolean);
  const technicalOpportunities = [!summary.canonical&&'Define a canonical URL for the primary page.',!summary.robots&&'Publish and validate robots.txt and ensure important pages are crawlable.',!summary.sitemapLink&&'Publish an XML sitemap and submit it to search engines.',!summary.securityHeaders?.hsts&&'Enable HSTS after confirming HTTPS is correctly enforced.',!summary.securityHeaders?.csp&&'Evaluate a Content-Security-Policy appropriate for the application.',!summary.securityHeaders?.referrerPolicy&&'Add a deliberate Referrer-Policy.'].filter(Boolean);
  const professional = {
    plan:'professional', categoryRows, executive:{ headline:data.score>=75?'The site has a solid foundation with targeted opportunities for growth.':'The site has meaningful improvement opportunities that should be prioritized before scaling traffic.', score:clamp(data.score), grade:grade(data.score), biggestOpportunity:categoryRows.slice().sort((a,b)=>a.score-b.score)[0]?.name||'Technical', passedChecks:passed.length, failedChecks:failed.length, estimatedEffort:failed.length>=10?'High':failed.length>=5?'Medium':'Low' },
    strengths, risks, recommendations, contentOpportunities, technicalOpportunities,
    performance:{ responseMs:Number(data.elapsed||0), responseGrade:Number(data.elapsed||0)<800?'Fast':Number(data.elapsed||0)<1500?'Acceptable':'Slow', imageCount:Number(summary.images||0), optimizationAdvice:Number(summary.images||0)>20?'Audit image dimensions, compression, modern formats and lazy loading.':'Review image dimensions and modern formats even if image count is moderate.', caveat:'Server response time is directional; browser-based Core Web Vitals testing is still recommended.' },
    actionPlan:['Week 1: Fix critical SEO, HTTPS, mobile and accessibility issues.','Week 2: Improve metadata, headings, schema, internal linking and conversion CTAs.','Week 3: Optimize images, scripts, caching and server response performance.','Week 4: Publish supporting content, validate indexing and re-run the audit.']
  };
  if (plan !== 'business') return professional;
  return { ...professional, plan:'business', businessSummary:{ commercialReadiness:clamp(s.content*.3+s.performance*.15+s.mobile*.15+s.security*.15+s.seo*.25), leadGenerationReadiness:clamp(contactSignals*25+(summary.forms?25:0)), trustReadiness:clamp((summary.https?35:0)+(summary.schema?20:0)+(summary.description?15:0)+(summary.ogTitle?10:0)+s.security*.2), contentDepth:clamp(Math.min(100,Number(summary.words||0)/10+Number(summary.h2||0)*5)) },
    conversionAudit:[{area:'Contactability',status:contactSignals>=2?'Present':'Weak',insight:contactSignals>=2?'Multiple contact signals were detected.':'Add prominent phone, WhatsApp, enquiry or booking actions.'},{area:'Lead capture',status:Number(summary.forms||0)>0?'Present':'Missing',insight:Number(summary.forms||0)>0?`${summary.forms} form(s) detected.`:'Consider a short lead form with a clear value proposition and privacy reassurance.'},{area:'Trust',status:summary.https&&summary.schema?'Good foundation':'Needs work',insight:'Strengthen trust with HTTPS, structured business information, testimonials, guarantees, credentials and transparent contact details.'},{area:'Mobile conversion',status:s.mobile>=70?'Ready for review':'Priority',insight:'Validate tap targets, sticky CTAs, form usability and above-the-fold messaging on real mobile devices.'}],
    strategicOpportunities:['Create dedicated landing pages for high-value services and customer segments.','Build proof assets: testimonials, case studies, credentials, outcomes and FAQs.','Connect every high-intent page to one primary conversion action and track it.','Use analytics and Search Console data to validate which recommendations produce commercial impact.','Re-run this audit monthly and after major site releases to detect regression.'],
    ninetyDayPlan:['Days 1–30: Resolve technical and conversion blockers; establish analytics and baseline KPIs.','Days 31–60: Publish service/segment landing pages, supporting content, FAQs and proof assets.','Days 61–90: Improve conversion funnels, test CTAs, strengthen internal linking and compare search/lead performance against the baseline.'],
    kpis:['Organic impressions','Organic clicks','Qualified leads','Lead conversion rate','Top landing-page conversion rate','Page response time','Indexed pages','Form/WhatsApp enquiries']
  };
}
